### ISSUE TITLE
Contact button in Call to action is not working

### ISSUE THREAD

**Issue by manujchandra** [Somrat37/somrat#23]
When we click the contact button in the call to action, it reloads the page, instead of scrolling to the contact section.

This is happening locally on latest version of hugo, its also happening on the demo page

Reproduce:
https://themes.gohugo.io/theme/somrat

Click on the button hello under need a service? Instead of taking to the contact page it will reload the page.

**Comment by somratpro** [comment]
use relURL instead of absURL

**Comment by manujchandra** [comment]
Hi, sorry new to Hugo.

In call-to-action.md

I have:

button:
  enable : true
  label : "Request a Callback"
  link : "#contact"

This is not working.

But in banner.md I have:

button:
  enable : true
  label : "LET'S SOLVE!"
  link : "#contact"

But this is working. Which means the button link in banner is working, but the same link in call to action is not working.

How to use relURL?

**Comment by voidcreativestudio** [comment]
@manujchandra go to index.html and find the call to action section. Change "absURL" to "relURL". I ran into this problem too! 
<img width="607" alt="Screenshot 2021-03-14 at 22 41 22" src="https://user-images.githubusercontent.com/80590937/111086951-e30d3380-8516-11eb-8331-04dd8b63713d.png">

**Comment by manujchandra** [comment]
Thanks @voidcreativestudio this solves it.
