### ISSUE TITLE
Service icons

### ISSUE THREAD

**Issue by stephenajulu** [Somrat37/somrat#4]
Hi, how are you? 
First I'd like to thank you very very much for this awesome theme.
Thank you.
Next i would like to ask, **where did you get the icons for the service section?**
I am using your theme and there are afew services i would like to add without ruining the look of the theme and if i get icons from somewhere else it might not look as asthetic.

**Comment by Somrat37** [comment]
hey, you are welcome. i get those icon in google. i just wrote the name of
the icon and search. then i choose icon from there. for example "database
line icon"
