### ISSUE TITLE
Best way to add additional pages for portfolio items? Portfolio issue as well.

### ISSUE THREAD

**Issue by MostHated** [Somrat37/somrat#6]
Hey there,
    I really like the theme you have created. it has a nice, slick feel to it. Thank you for sharing it. 

I do apologize though, as I am brand new to Hugo (just started with it a few days ago). I got Forestry.io setup and connected to my site and I wanted to try to make it so that going to a portfolio item can give you the ability to not only view an image but in the slide-over name view, let you click to take you to a new page that is somewhat similar to the "About me" section that can have additional information about the 

I am wondering if that is possible with how this theme is set up? I saw that with the default forestry configuration it had the ability to add a new page, but you had to create a template for the fields and such, so I tried to see if I could use the homepage as a template to then create a new page for the portfolio items, but I am honestly just not sure how I am supposed to go about trying to implement that and link to it from the main page using the theme, or forestry.io. 

When I tried to use the homepage as a template, I created a new page and just filled out the about section quickly with a name and a small bit of data and then tried to save it, pulled that down to my PC, and then tried to build it, I ended up getting the following error straight away:

```
Error: Error building site: failed to load data: failed to load data: "E:\GitHub\instance-id.github.io\data\en\searcher.md:1:1": unmarshal of 
format "" is not supported
```

The file it created contained markdown data, but I am guessing that is not what it should end up being? I am just not sure exactly how I should go about making the new pages. Do you happen to have any suggestions or recommendations on what would be the best way to accomplish this with this theme?

-----------------------------------------------
A secondary issue. I am not sure if it is perhaps something I goofed up, but fairly often when I first load the page, the portfolio section will be overlapping and not laid out properly. As soon as I resize the width of the browser any sort of amount, they go right where they should as seen here: https://i.imgur.com/zvL87OE.mp4 As soon as I reload, they overlap again. 

Thanks,
-MH

**Comment by Somrat37** [comment]
hey there, i am sorry to say that i didn't work on this project anymore. This issue will be active until someone will help you. Best of luck 👍

**Comment by MostHated** [comment]
It's fine. Hugo ended up being quite easy to figure out so I just rolled my own custom setup for everything. I did still use the filterizr plugin for the images and was able to get the issue worked out by using another small library called "imagesLoaded".

Thanks,
-MH
