### ISSUE TITLE
Issue Compiling hugo

### ISSUE THREAD

**Issue by 786country** [Somrat37/somrat#7]
Hi @Somrat37 

I really love your theme, I have a issue that when i run the 
`cd somrat/exampleSite/`
and then `hugo server --themesDir ../..`

the websites compiles correctly. 

however when I try making the public files my website does not render correctly. Is there a certain method to run the hugo command?

**Comment by lsrdg** [comment]
Hi, have you found an answer to this? I am trying to publish to Gitlab Pages and it does not render correctly. I am not sure if the problem is in `.gitlab-ci.yml` (in the build command) or in `content/config.toml`. Any ideas on the issue would be appreciated. (:
Cheers!

**Comment by lsrdg** [comment]
For anyone coming in here with the same issue:

Apparently, there's nothing wrong with the theme itself, but maybe with the documentation which guides the user to `$ cd exampleSite` and run run the server from `exampleSite/`.

My solution was basically move the relevant files from `exampleSite/` to the root directory (and forget the exampleSite. By doing that, `.gitlab-ci.yml` got simplified to just running `$ hugo`.

If - for any reason - there is a need of keeping the site into the `exampleSite/`, taking a look at `netlify.toml` might give a hint on how to perform the build:
`$ cd exampleSite && hugo --gc --themesDir ../..".

Thanks @somratpro for the great theme! And if I got the issue right, let me know if I can help with the docs.
